name: CI

on:
  push:
    branches: [ codex/bootstrap-codex-playbook-repository ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Upgrade pip (no extra deps)
        run: python -m pip install --upgrade pip

      - name: Run tests
        run: bash scripts/test.sh
